name = "rss-translator"
main = "src/worker.ts"
compatibility_date = "2024-04-01"

# 每 10 分钟预缓存翻译好的文章正文
[triggers]
crons = ["*/10 * * * *"]

[vars]
LOG_LEVEL = "info"

[[kv_namespaces]]
binding = "RSS_CONFIG"
id = "e47f4fc3903443f6bc8e359928ab5b5c"

[[kv_namespaces]]
binding = "RSS_ARTICLE_CACHE"
id = "df144d8668a14e7c92da5c1545957c6d"
